---
- name: Make sure /etc/zabbix/zabbix_agentd.d/ exists
  file: path=/etc/zabbix/zabbix_agentd.d/ state=directory owner=zabbix group=zabbix mode=0755
- name: Copy userparameter file
  copy: src=userparameter_passenger.conf dest=/etc/zabbix/zabbix_agentd.d/userparameter_passenger.conf owner=zabbix group=zabbix mode=0644
