---
- name: install tomcat
  apt: name={{ item }} update_cache=yes state=present
  with_items:
  - tomcat7
  - tomcat7-common
  - tomcat7-admin

- name: configure tomcat users
  template: src=tomcat-users.j2 dest=/var/lib/tomcat7/conf/tomcat-users.xml
  notify: restart tomcat7

- name: configure tomcat defaults and java
  template: src=tomcat7-defaults.j2 dest=/etc/default/tomcat7
  notify: restart tomcat7
