---
- name: Configure DNS suffix appending
  lineinfile: dest=/etc/dhcp/dhclient.conf insertafter='send host-name' line='supersede domain-search "{{ dns_suffix }}";' regexp='supersede domain-search'
  notify:
  - run dhclient

- name: clean out /etc/hosts
  template: src=etc_hosts.j2 dest=/etc/hosts